name: Bug report
description: Report something that isn't working
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: What happened?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Run ...
        2. See ...
    validations:
      required: true
  - type: input
    attributes:
      label: Environment
      placeholder: "OS, Go version, trooper version"
